name: "Security Scans"
description: "Runs security scans on the app"
inputs:
  github-requirements-branch:
    description: 'Branch of the github requirements repository to check out'
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run Security Scans
      run: |
        app_json=$(find . -maxdepth 1 -name '*.json' ! -name '*.postman_collection.json')
        publisher=$(jq -r '.publisher' "$app_json")
        is_splunk_supported=false
        if [[ "$publisher" == "Splunk" ]]; then
          set -e
          is_splunk_supported=true
        else
          echo "Security scans will not fail for community or developer supported apps. The SOAR team will handle the results"
          set +e
        fi

        python ${{ github.action_path }}/run_gitlab_pipeline.py 'GitHub Requirements' ${{ inputs.github-requirements-branch }} -t 600 -v "{
          \"APP_REPO_NAME\":\"${{ github.event.pull_request.head.repo.name }}\",
          \"APP_REPO_BRANCH\":\"${{ github.event.pull_request.head.ref }}\",
          \"APP_REPO_OWNER\":\"${{ github.event.pull_request.head.repo.owner.login }}\",
          \"SPLUNK_SUPPORTED\":\"$is_splunk_supported\"
        }"
        if [[ "$is_splunk_supported" == "false" ]]; then
          exit 0
        fi
      shell: bash
