name: "Precommit"
description: "Runs pre-commit on the pushed code"
runs:
  using: "composite"
  steps:

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip pre-commit
        pre-commit install

    - name: Run pre-commit
      shell: bash
      run: pre-commit run --all-files
      continue-on-error: true # TODO: remove this on real deployment

    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-cache
