name: "Precommit"
description: "Runs pre-commit on the pushed code"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: pip
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip pre-commit
        pre-commit install
    
    - name: Run pre-commit
      shell: bash
      run: pre-commit run --all-files
      continue-on-error: true # TODO: remove this on real deployment
