name: "Test coverage"
description: "Determines if all of the connectors actions are being tested"
inputs:
  app_repo:
    description: "Connector repo being tested"
    required: true

runs:
  using: composite
  steps:
    - name: Clone app tests repo
      env:
        APP_TESTS_BRANCH: ${{ github.head_ref || github.ref_name }}
      shell: bash
      run: |
        cd ..
        git clone https://oauth2:$GITLAB_API_TOKEN@cd.splunkdev.com/phantom-apps/app-tests.git

    - name: Determine test coverage
      shell: bash
      run: |
        cd ../app-tests
        if ! git checkout origin/$APP_TESTS_BRANCH &> /dev/null; then
          echo "Could not find app-tests branch $APP_TESTS_BRANCH, defaulting to main."
          git checkout main
        fi
        if [[ ! -d suite/apps/"${{ inputs.app_repo }}" ]]; then
          echo "ERROR - expected to find test suite for Splunk supported app ${{ inputs.app_repo }}"
          exit 1
        fi
        pytest suite/apps/"${{ inputs.app_repo }}" --color=yes --collect-actions --collect-output tested_actions.json
        cd ..
        python ${{ github.action_path }}/determine_test_coverage.py ${{ github.event.repository.name }} --dir-location=$(pwd)
