name: Reusable Publish Workflow

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip

      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Publish
        uses: ./.github/actions/publish