name: SDKfied App Setup
description: "Sets up UV environment"
inputs:
  uv_lock_directory:
    description: 'Directory containing uv.lock file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv for SDKfied apps
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash
    
    - name: Setup UV Environment
      run: |
        cd "${{ inputs.uv_lock_directory }}"
        uv add splunk-soar-sdk
        uv sync
        echo "UV environment setup completed successfully"
      shell: bash

