name: Connector contract summary

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  contract-summary:
    uses: splunk-soar-connectors/.github/.github/workflows/contract.yml@main
