name: "Aggregate Sanity Results"
description: "Aggregates sanity test results from all matrix jobs and creates a summary report"
inputs:
  artifacts_path:
    description: 'Path where sanity test artifacts are downloaded'
    required: false
    default: 'downloaded-artifacts'
runs:
  using: "composite"
  steps:
    - name: Strip ANSI codes from all artifacts
      shell: bash
      run: |
        echo "Stripping ANSI codes from all test artifacts..."
        for artifact_dir in ${{ inputs.artifacts_path }}/sanity-test-results-*/; do
          if [ -d "$artifact_dir" ]; then
            version=$(basename "$artifact_dir" | sed 's/sanity-test-results-//')
            echo "Processing $version..."

            raw_log="${artifact_dir}pytest-output-raw.log"
            clean_log="${artifact_dir}pytest-output.log"

            if [ -f "$raw_log" ]; then
              python3 ${{ github.action_path }}/strip_ansi.py "$raw_log" "$clean_log"
              echo "  ✓ Cleaned $version log"
            else
              echo "  ⚠ No raw log found for $version"
            fi
          fi
        done
        echo "ANSI code stripping complete"

    - name: Upload cleaned logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sanity-test-results-cleaned
        path: ${{ inputs.artifacts_path }}/*/pytest-output.log
        retention-days: 7
        if-no-files-found: warn

    - name: Aggregate Results
      run: |
        set -e
        python3 ${{ github.action_path }}/aggregate_results.py --artifacts-path ${{ inputs.artifacts_path }}
      shell: bash
