name: "Publish"
description: "Publishes the app to Splunkbase"
runs:
  using: "composite"
  steps:
  - name: Publish App
    run: |
      set -e
      python ${{ github.action_path }}/upload_to_splunkbase.py ${{ github.event.repository.name }} --splunkbase_env "$SPLUNKBASE_ENV"
    shell: bash
