name: "Publish"
description: "Publishes the app to Splunkbase"
runs:
  using: "composite"
  steps:
  - name: Publish App
    id: publish_app
    run: |
      set +e
      python ${{ github.action_path }}/upload_to_splunkbase.py ${{ github.event.repository.name }}
      return_code=$?
      echo return_code=$return_code >> $GITHUB_ENV
    shell: bash
    env:
      SEND_RELEASE_MESSAGE: ${{ vars.SEND_RELEASE_MESSAGE }}
