name: "Publish"
description: "Publishes the app to Splunkbase"
inputs:
  is_sdkfied:
    description: 'Whether this is an SDKfied app (true/false)'
    required: true
runs:
  using: "composite"
  steps:
  - name: Publish App
    id: publish_app
    run: |
      set +e
      cd $GITHUB_WORKSPACE
      python ${{ github.action_path }}/upload_to_splunkbase.py ${{ github.event.repository.name }}
      return_code=$?
      echo return_code=$return_code >> $GITHUB_ENV
    shell: bash
