name: "Build App"
description: "Builds the app"
runs:
  using: "composite"
  steps:
    - name: echo
      run: |
            echo ${{ github.action_path }}
            echo ${{ github.ref_name }}
            echo ${{ github.repository }}
            echo ${{ github.base_ref }}
            echo ${{ github.head_ref }}
            ls -lath
      shell: bash

    - name: Install Requirements
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Build App
      run: python ${{ github.action_path }}/build_app.py -b ${{ github.base_ref }} ${{ github.repository }} --dry-run
      shell: bash
