name: "Build App"
description: "Builds the app"
runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Set Branch Name
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build App
      run: |
        python ${{ github.action_path }}/build_app.py ${{ github.event.repository.name }} $BRANCH_NAME --output-dir=$(pwd)
      shell: bash
