name: "Build App"
description: "Builds the app"
runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Build App
      run: |
        echo ${{ github.event.repository.name }} ${{ github.ref_name }}
        python ${{ github.action_path }}/build_app.py ${{ github.event.repository.name }} ${{ github.ref_name }} --output-dir=$(pwd)
      shell: bash
