name: "Build App"
description: "Builds the app"
runs:
  using: "composite"
  steps:
    - name: echo
      run: |
            echo ${{ github.action_path }}
            ls -lath
      shell: bash

    - name: Install Requirements
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Build App
      run: python ${{ github.action_path }}/build_app.py
      shell: bash
