name: "Build App"
description: "Builds the app"
runs:
  using: "composite"
  steps:
    - name: echo
      run: echo ${{ github.action_path }}
      shell: bash

    - name: Build App
      run: python ${{ github.action_path }}/build_app.py
      shell: bash
