name: "Sanity Tests"
description: "Runs sanity tests on the app"
inputs:
  phantom_ip:
    description: "Phantom instance the tests are ran on"
    required: true
  version:
    description: "Phantom version being tested"
    required: true
  app_repo:
    description: "Connector repo being tested"
    required: true
  automation_broker:
    description: "Automation broker to use for cloud tests"
    required: false
runs:
  using: "composite"
  steps:
    - name: Clone necessary repositories
      shell: bash
      run: |
        cd ..
        if [ ! -d "app-tests" ]; then
          git clone https://oauth2:$GITLAB_API_TOKEN@cd.splunkdev.com/phantom-apps/app-tests.git
        else
          echo "Repository 'app-tests' already exists. Skipping clone."
        fi
    - name: Run app tests
      env:
        APP_TESTS_BRANCH: ${{ github.head_ref || github.ref_name }}
      shell: bash
      run: |
        phantom_ip=${{ inputs.phantom_ip }}
        export PHANTOM_URL="https://$phantom_ip"
        python ${{ github.action_path }}/../../utils/app_rest_installer.py $phantom_ip $PHANTOM_USERNAME $PHANTOM_PASSWORD
        