name: "Compile App"
description: "Compiles the app on a SOAR instance"
runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Compile App
      run: |
        set -e
        python ${{ github.action_path }}/compile_app_in_instance.py --local-code-dir pwd --app-repo-branch ${{ github.event.repository.name }} ${{ github.head_ref }} 2>&1 | tee compile_app.out
      shell: bash
