name: "Compile App"
description: "Compiles the app on a SOAR instance"
runs:
  using: "composite"
  steps:
    - name: Compile App
      run: |
        set -e
        python3 compile_app_in_instance.py "$APP_REPO" $REPO_BRANCH_FLAG \
                $FORK_OWNER_FLAG $FORK_REPO_FLAG 2>&1 | tee compile_app.out
      shell: bash
