name: Reusable Publish Workflow

on:
  workflow_call:

jobs:
  semantic-version:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Environment
          uses: splunk-soar-connectors/.github/.github/actions/env-setup@main

        - name: Set up .github repo
          uses: actions/checkout@v4
          with:
            repository: splunk-soar-connectors/.github
            path: dotgithub

        - name: Copy necessary files to app repo for semantic release
          run: |
            ls -lath
            cp dotgithub/.releaserc.json $(pwd)/.releaserc.json
            cp dotgithub/.github/actions/publish/utils/update_version.py $(pwd)/update_version.py
            ls -lath

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "lts/*"

        - name: Install dependencies
          run: |
            npm install --save-dev semantic-release
            npm install @semantic-release/changelog @semantic-release/git @semantic-release/exec -D

        - name: Run semantic-release and update version numbers
          env:
            GITHUB_TOKEN: ${{ github.token }}
          run: |
            npx semantic-release -e $(pwd)/.releaserc.json

  build:
    runs-on: ubuntu-latest
    needs: semantic-version
    steps:
      - name: Setup Environment
        uses: splunk-soar-connectors/.github/.github/actions/env-setup@main

      - name: Clean up
        run: |
          pwd
          ls -lath
          if [ -f package.json ]; then
            rm package.json
          fi
          if [ -f package-lock.json ]; then
            rm package-lock.json
          fi
          if [ -f .releaserc.json ]; then
            rm .releaserc.json
          fi
          if [ -d dotgithub ]; then
            rm -rf dotgithub
          fi

      - name: Build Application
        uses: splunk-soar-connectors/.github/.github/actions/build-app@mnordby/PAPP-35411

      - name: Upload app tar file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-tar
          path: ${{ github.event.repository.name }}.tgz

  publish:
    runs-on:
      - codebuild-integration-tests-${{ github.run_id }}-${{ github.run_attempt }}
      - image:custom-linux-875003031410.dkr.ecr.us-west-2.amazonaws.com/soar-connectors/pytest:f7150dbb7f347d35f8f4bb285d36985ecd4cf231
    needs: build
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Download app tar file for upload
        uses: actions/download-artifact@v4
        with:
          name: app-tar
          path: artifacts/

      - name: Publish
        uses: splunk-soar-connectors/.github/.github/actions/publish@mnordby/PAPP-35411
        env:
          UPLOAD_PATH: "artifacts/${{ github.event.repository.name }}.tgz"
