name: Reusable Publish Workflow

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Publish
        uses: splunk-soar-connectors/.github/actions/publish@main
