name: Reusable Push Workflow

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: splunk-soar-connectors/.github/.github/actions/env-setup@main

      - name: Pre-commit
        uses: splunk-soar-connectors/.github/.github/actions/pre-commit@main

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Setup Environment
        uses: splunk-soar-connectors/.github/.github/actions/env-setup@main

      - name: Build Application
        uses: splunk-soar-connectors/.github/.github/actions/build-app@main

      - name: Upload app tar file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-tar
          path: ${{ github.event.repository.name }}.tgz

  compile:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: pre-commit
    steps:
      - name: Setup Environment
        uses: splunk-soar-connectors/.github/.github/actions/env-setup@main

      - name: Compile Application
        uses: splunk-soar-connectors/.github/.github/actions/compile-app@main

  test-setup:
    runs-on: ubuntu-latest
    needs: [build, compile]
    outputs:
      fips_compliant: ${{ steps.set-outputs.outputs.fips_compliant }}
      publisher: ${{ steps.set-outputs.outputs.publisher }}
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Set sanity tests enviornment variables
        uses: splunk-soar-connectors/.github/.github/actions/test-setup@main

      - name: Set outputs
        id: set-outputs
        run: |
          echo "publisher=${{ env.publisher }}" >> $GITHUB_OUTPUT
          echo "fips_compliant=${{ env.fips_compliant }}" >> $GITHUB_OUTPUT

  sanity-test:
    runs-on:
      - codebuild-integration-tests-${{ github.run_id }}-${{ github.run_attempt }}
      - image:custom-linux-875003031410.dkr.ecr.us-west-2.amazonaws.com/soar-connectors/pytest:f7150dbb7f347d35f8f4bb285d36985ecd4cf231
    needs: [build, compile, test-setup]
    strategy:
      matrix:
        include:
          - version: "current"
            ip: ${{ vars.PHANTOM_INSTANCE_CURRENT_VERSION_IP }}
          - version: "next"
            ip: ${{ vars.PHANTOM_INSTANCE_NEXT_VERSION_IP }}
          - version: "previous"
            ip: ${{ vars.PHANTOM_INSTANCE_PREVIOUS_VERSION_IP }}
          - version: "cloud"
            ip: ${{ vars.PHANTOM_INSTANCE_CLOUD_HOST }}
          - version: "rhel"
            ip: ${{ vars.PHANTOM_INSTANCE_CURRENT_RHEL_VERSION_IP }}
    env:
      AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP: ${{ vars.AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP }}
      AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP: ${{ vars.AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP }}
      NUM_TEST_RETRIES: ${{ vars.NUM_TEST_RETRIES }}
      VAULT_ROLE: ${{ vars.VAULT_ROLE }}
      PHANTOM_INSTANCE_CURRENT_FIPS_VERSION_IP: ${{ vars.PHANTOM_INSTANCE_CURRENT_FIPS_VERSION_IP }}

    steps:
      - uses: actions/checkout@v4

      - name: Download app tar file
        uses: actions/download-artifact@v4
        with:
          name: app-tar

      - name: Run Sanity Tests
        uses: splunk-soar-connectors/.github/.github/actions/sanity-tests@main
        with:
          fips_compliant: ${{ needs.test-setup.outputs.fips_compliant }}
          publisher: ${{ needs.test-setup.outputs.publisher }}
          phantom_ip: ${{ matrix.ip }}
          version: ${{ matrix.version }}
          app_repo: ${{ github.event.repository.name }}

  integration-test:
    runs-on:
      - codebuild-integration-tests-${{ github.run_id }}-${{ github.run_attempt }}
      - image:custom-linux-875003031410.dkr.ecr.us-west-2.amazonaws.com/soar-connectors/pytest:f7150dbb7f347d35f8f4bb285d36985ecd4cf231
    needs: [build, compile, test-setup]
    env:
      PHANTOM_INSTANCE_IP: ${{ vars.PHANTOM_INSTANCE_IP }}
      PHANTOM_INSTANCE_IP_FIPS: ${{ vars.PHANTOM_INSTANCE_IP_FIPS }}
      AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP: ${{ vars.AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP }}
      AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP: ${{ vars.AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP }}
      NUM_TEST_RETRIES: ${{ vars.NUM_TEST_RETRIES }}
      VAULT_ROLE: ${{ vars.VAULT_ROLE }}
    steps:
      - uses: actions/checkout@v4

      - name: Download app tar file
        uses: actions/download-artifact@v4
        with:
          name: app-tar

      - name: Run Integration Tests
        uses: splunk-soar-connectors/.github/.github/actions/integration-tests@main
        with:
          fips_compliant: ${{ needs.test-setup.outputs.fips_compliant }}
          publisher: ${{ needs.test-setup.outputs.publisher }}
          app_repo: ${{ github.event.repository.name }}

  security-scans:
    runs-on: ubuntu-latest
    needs: [build, compile]
    steps:
      - name: Setup Environment
        uses: splunk-soar-connectors/.github/.github/actions/env-setup@main

      - name: Run Security Scans
        uses: splunk-soar-connectors/.github/.github/actions/security-scans@main
