name: Reusable Push Workflow

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Pre-commit
        uses: splunk-soar-connectors/.github/.github/actions/pre-commit@main

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build Application
        uses: splunk-soar-connectors/.github/.github/actions/build-app@main

  compile:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: pre-commit
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Compile Application
        uses: splunk-soar-connectors/.github/.github/actions/compile-app@main

  sanity-test:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: [build, compile]
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Sanity Tests
        uses: splunk-soar-connectors/.github/.github/actions/sanity-tests@main

  integration-test:
    runs-on: 
      - codebuild-integration-tests-${{ github.run_id }}-${{ github.run_attempt }}
      - image:custom-linux-875003031410.dkr.ecr.us-west-2.amazonaws.com/soar-connectors/pytest:f7150dbb7f347d35f8f4bb285d36985ecd4cf231
    needs: [build, compile]
    env:
      APP_REPO: ${{ github.event.repository.name }}
      PHANTOM_INSTANCE_IP: ${{ vars.PHANTOM_INSTANCE_IP }} 
      PHANTOM_INSTANCE_IP_FIPS: ${{ vars.PHANTOM_INSTANCE_IP_FIPS }}
      AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP: ${{ vars.AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP }}
      AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP: ${{ vars.AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP }}
      NUM_TEST_RETRIES: ${{ vars.NUM_TEST_RETRIES }}
      VAULT_ROLE: ${{ vars.VAULT_ROLE }}
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Run Integration Tests
        uses: splunk-soar-connectors/.github/.github/actions/integration-tests@main
  
  security-scans:
    runs-on: ubuntu-latest
    needs: [build, compile]
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Security Scans
        uses: splunk-soar-connectors/.github/.github/actions/security-scans@main
