name: Reusable Push Workflow

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Pre-commit
        uses: ./.github/actions/pre-commit

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Build Application
        uses: ./.github/actions/build-app

  compile:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: pre-commit
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Compile Application
        uses: ./.github/actions/compile-app

  sanity-test:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: [build, compile]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Run Sanity Tests
        uses: ./.github/actions/sanity-tests

  integration-test:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: [build, compile]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Run Integration Tests
        uses: ./.github/actions/integration-tests
  
  security-scans:
    runs-on: ubuntu-latest
    needs: [build, compile]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out app repo
        uses: actions/checkout@v4

      - name: Run Security Scans
        uses: ./.github/actions/security-scans
