name: Reusable Push Workflow

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out actions repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Pre-commit
        uses: splunk-soar-connectors/.github/.github/actions/pre-commit@main

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build Application
        uses: splunk-soar-connectors/.github/.github/actions/build-app@main

  compile:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: pre-commit
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Compile Application
        uses: splunk-soar-connectors/.github/.github/actions/compile-app@main

  sanity-test:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: [build, compile]
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Sanity Tests
        uses: splunk-soar-connectors/.github/.github/actions/sanity-tests@main

  integration-test:
    runs-on: ubuntu-latest # This will be Codebuild
    needs: [build, compile]
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Integration Tests
        uses: splunk-soar-connectors/.github/.github/actions/integration-tests@main
  
  security-scans:
    runs-on: ubuntu-latest
    needs: [build, compile]
    steps:
      - name: Check out app repo
        uses: actions/checkout@v4
        with:
          repository: splunk-soar-connectors/.github  # Explicitly check out .github repo for actions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Security Scans
        uses: splunk-soar-connectors/.github/.github/actions/security-scans@main
